### PR TITLE
Removed special handling of success being 0 or 1 (issue #117)

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,
Thanks! Could you please describe this change a little bit? I’m lacking any context...

**Comment by SebastianZ** [comment]
Ok, here's the calculation:

You have 7 classes, though you put 2 out, so 5 remain.
So, imagine you have 7 tests like for `calc()` (see issue #117) and one of those tests fails, your calculation `Math.round((6 / 7) * (5 - 1))` results in `3` meaning the `slightly-buggy` class.

Though for a correct calculation you need to take all 7 classes into account. Then the calculation is  `Math.round((6 / 7) * (7 - 1))`, which results in `5`, i.e. the class `almost-pass`.

Is it clearer now?

Sebastian

**Comment by LeaVerou** [comment]
Merged, thanks!

**Comment by SebastianZ** [comment]
Thank you for merging and a Happy New Year 2016!

Sebastian

**Pull request merged**
