### PR TITLE
Add descriptor tests for @counter-style

### PR DESCRIPTION
**Pull request by Zefling**
I had to make lots of exceptions to be able to test @counter-style completely. I don't know if it can be accepted.

image

### CODE REVIEW

**Comment by LeaVerou** [comment]
thank you for working on this. However, I don't think adding exceptions for specific rules in the testing code is a good way forward. Instead of making exceptions for specific rules, we should add extensibility points so that the tests that need exceptions can define whatever exceptions they need themselves. Otherwise, if in the future we need to make more exceptions, the code will become a mess.

**Comment by Zefling** [comment]
Sure, but since some rules require other rules or ownership, I don't know how to do otherwise except add optional extra test points (in test.js) for each test.
It was really complicated to make sure the tests were valid.

**Comment by Zefling** [comment]
I changed for rules in tests.js

**Comment by Zefling** [comment]
@LeaVerou Is it not good ?

**Pull request merged**
