### PR TITLE
Adding `min/max/fit-content` and `fit-content()` values to `flex-basis` and `flex`

### PR DESCRIPTION
**Pull request by yisibl**
- MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
- Chrome status: https://chromestatus.com/feature/5635933158244352

### CODE REVIEW

**Comment by yisibl** [comment]
@LeaVerou PTAL, thanks!

**Review by LeaVerou — APPROVED** [review]
LGTM, thanks!

**Comment by SebastianZ** [comment]
I think it would make more sense to define those as _values_ in CSS Box Sizing 3 and 4 and add `flex-basis` and `flex` there. Those values are defined in those specs and `flex-basis` just refers to `<'width'>` in its syntax.

Sebastian

**Review by SebastianZ — CHANGES_REQUESTED** [review]
I think it would make more sense to define those as values in CSS Box Sizing 3 and 4 and add flex-basis and flex there. Those values are defined in those specs and flex-basis just refers to <'width'> in its syntax.

Sebastian

**Comment by SebastianZ** [comment]
Btw. regarding the state of the `fit-content` keyword vs. the `fit-content()` function, I just filed https://github.com/w3c/csswg-drafts/issues/10601.

Sebastian

**Comment by yisibl** [comment]
@SebastianZ  It makes sense to add separate tests to flex properties to help users more visually see how they are supported in different properties.

**Comment by SebastianZ** [comment]
> @SebastianZ It makes sense to add separate tests to flex properties to help users more visually see how they are supported in different properties.

I'm still not totally happy with this, but given that Chrome explicitly implements it for `flex-basis` and `flex`, I guess it's ok.

Though we should ensure the values are also tested in the Box Sizing specs for other properties.

Sebastian

**Pull request merged**
