### PR TITLE
Links correction, add level number

### PR DESCRIPTION
**Pull request by Zefling**
- Show the module « Level » for all modules
- Correct all links (tr / dev)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey there, thanks for the contribution!
Given that this is a pretty extensive change, is this online somewhere so I can check it out?
Thanks!

**Comment by Zefling** [comment]
No problem. I will wait your feedback.

**Comment by LeaVerou** [comment]
Um, I think you missed my question…

> is this online somewhere so I can check it out?

**Comment by Zefling** [comment]
Like this : http://test.ikilote.net/projets/css3test/ ?

**Comment by Zefling** [comment]
Is it not good ? I have update the pull request.

**Comment by LeaVerou** [comment]
Thanks, I had missed your first post!
I think it's very confusing, UI-wise. I thought it was number of tests or something, and struggled figuring out what the number was. I had to read your first comment to realize, otherwise I would have never guessed. Furthermore, when it matters the level is already in the name, so I'm not sure why this is needed.
Thanks for putting effort into css3test and I hope this does not put you off future contributions!

**Pull request closed without merging**
